"""Small genuine Matterhorn XML snapshot for integration testing.

These records were transcribed from the user-provided productsAUD.xml catalogue.
They are source-backed but NOT live inventory. Supplier cost stays private and is
never exposed as a LUMIÈRE customer price.
"""

MATTERHORN_TRIAL_SNAPSHOT = [
    {
        "external_id": "111506",
        "name": "Blouse model 111506 Figl",
        "brand": "Figl",
        "category": "Women’s Blouses, Tunics",
        "description": "Simple blouse with short sleeves in olive color. Perfect for everyday wear.",
        "price": 12.9,
        "currency": "AUD",
        "image_url": "https://matterhorn-wholesale.com/pics_source/311639.jpg",
        "source_url": None,
        "colour_names": ["green", "olive"],
        "sizes": ["S", "M", "L"],
        "materials": ["Spandex 5%", "Polyester 95%"],
        "occasions": [],
        "palette_tags": [],
        "availability": "11",
    },
    {
        "external_id": "135767",
        "name": "Blouse model 135767 Figl",
        "brand": "Figl",
        "category": "Women’s Blouses, Tunics",
        "description": "Navy blue charming sleeveless double layer blouse with a half round neckline, flared out to the bottom.",
        "price": 24.9,
        "currency": "AUD",
        "image_url": "https://matterhorn-wholesale.com/pics_source/855570.jpg",
        "source_url": None,
        "colour_names": ["navy blue"],
        "sizes": ["S", "M"],
        "materials": ["Spandex 3%", "Polyester 80%", "Viscose 17%"],
        "occasions": [],
        "palette_tags": [],
        "availability": "20",
    },
    {
        "external_id": "150432",
        "name": "Blouse model 150432 Figl",
        "brand": "Figl",
        "category": "Women’s Blouses, Tunics",
        "description": "Green shirtcut blouse with a collar with two vertical pleats and long sleeves.",
        "price": 26.9,
        "currency": "AUD",
        "image_url": "https://matterhorn-wholesale.com/pics_source/894609.jpg",
        "source_url": None,
        "colour_names": ["green"],
        "sizes": ["XL"],
        "materials": ["Spandex 4%", "Polyester 30%", "Viscose 66%"],
        "occasions": [],
        "palette_tags": [],
        "availability": "5",
    },
    {
        "external_id": "8411",
        "name": "Tunic model 8411 Figl",
        "brand": "Figl",
        "category": "Women’s Blouses, Tunics",
        "description": "Tunic with halter neckline and decorative pleats at the neck.",
        "price": 33.9,
        "currency": "AUD",
        "image_url": "https://matterhorn-wholesale.com/pics_source/22316.jpg",
        "source_url": None,
        "colour_names": ["blue"],
        "sizes": ["M", "L", "XL"],
        "materials": [],
        "occasions": [],
        "palette_tags": [],
        "availability": "29",
    },
]
